name: RDP

on:
  workflow_dispatch:
    inputs:
      ngrok_region:
        description: 'Region (ap = Singapore)'
        required: false
        default: 'ap'

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 1450

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup RDP
        run: |
          Invoke-WebRequest -Uri "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath ngrok
          .\ngrok\ngrok.exe authtoken 3CALF22QQXcRRx5hlCGVyW04O5S_2VerPxZYcFEnDCuiJjgwV
          
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          New-LocalUser "DucthengTechDz" -Password (ConvertTo-SecureString "W1nd0ws-P4ssw0rd-2025!" -AsPlainText -Force)
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "DucthengTechDz"
          Add-LocalGroupMember -Group "Administrators" -Member "DucthengTechDz"
          
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name "fEnableVirtualizedGraphics" -Value 1 -Type DWord -Force
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name "AVCHardwareEncodePreferred" -Value 1 -Type DWord -Force
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name "MinFrameRate" -Value 120 -Type DWord -Force
          Set-ItemProperty -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services' -Name "fDisableWallpaper" -Value 1 -Type DWord -Force
          powercfg /setactive a1841308-3541-4fab-bc81-f71556f20b4a
          
          Start-Process -FilePath ".\ngrok\ngrok.exe" -ArgumentList "tcp 3389 --region=${{ github.event.inputs.ngrok_region }}" -NoNewWindow
          Start-Sleep -Seconds 5
          
          $response = Invoke-WebRequest -Uri "http://127.0.0.1:4040/api/tunnels" -UseBasicParsing
          $tunnelUrl = ($response.Content | ConvertFrom-Json).tunnels[0].public_url -replace 'tcp://', ''
          
          # LƯU CREDENTIALS RA FILE
          @"
          NGROK_URL=$tunnelUrl
          RDP_USER=DucthengTechDz
          RDP_PASS=W1nd0ws-P4ssw0rd-2025!
          "@ | Out-File -FilePath rdp-info.txt -Encoding utf8
          
          # COMMIT FILE LÊN REPO
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add rdp-info.txt
          git commit -m "Update RDP info" || exit 0
          git push
          
          Start-Sleep -Seconds 86400
